SKIP_DIRS = {
    ".git",
    ".venv",
    "__pycache__",
    "node_modules",
    ".idea",
    ".vscode",
    ".DS_Store",
    "LICENSE",
    "uv.lock",
    ".python-version",
    ".env",
    ".pytest_cache",
}

TEXT_EXTENSIONS = {
    ".txt",
    ".md",
    ".py",
    ".js",
    ".html",
    ".css",
    ".json",
    ".xml",
    ".yml",
    ".yaml",
    ".ini",
    ".cfg",
    ".conf",
    ".log",
    ".csv",
    ".sql",
    ".sh",
    ".bat",
    ".ps1",
    ".rb",
    ".go",
    ".java",
    ".cpp",
    ".c",
    ".h",
    ".php",
    ".pl",
    ".r",
    ".scala",
    ".kt",
    ".swift",
    ".ts",
    ".jsx",
    ".tsx",
    ".vue",
    ".svelte",
    ".sass",
    ".scss",
    ".less",
    ".dockerfile",
    ".gitignore",
    ".env",
    ".toml",
    ".lock",
}

EXT_MAPPING = {
    ".py": "python",
    ".js": "javascript",
    ".ts": "typescript",
    ".html": "html",
    ".css": "css",
    ".scss": "scss",
    ".sass": "sass",
    ".json": "json",
    ".xml": "xml",
    ".yml": "yaml",
    ".yaml": "yaml",
    ".sql": "sql",
    ".sh": "bash",
    ".bat": "batch",
    ".ps1": "powershell",
    ".rb": "ruby",
    ".go": "go",
    ".java": "java",
    ".cpp": "cpp",
    ".c": "c",
    ".h": "c",
    ".php": "php",
    ".pl": "perl",
    ".r": "r",
    ".scala": "scala",
    ".kt": "kotlin",
    ".swift": "swift",
    ".jsx": "jsx",
    ".tsx": "tsx",
    ".vue": "vue",
    ".dockerfile": "dockerfile",
    ".md": "markdown",
    ".toml": "toml",
}